### Demo 1: Matrix Inversion is Unstable

In [ ]:
import numpy as np
from scipy.linalg import hilbert
from sklearn.linear_model import LinearRegression

np.set_printoptions(linewidth=10000, suppress=True)

In [ ]:
np.random.seed(2109)
A = np.random.rand(12, 12)
print(A)

[[0.61284048 0.93157776 0.97676223 0.41667236 0.31897329 0.4578153  0.55323129 0.34643117 0.16127365 0.00418144 0.0550445  0.10626032]
 [0.75268907 0.22325695 0.09816058 0.29448169 0.47226834 0.11204482 0.88129521 0.14927572 0.57249316 0.02332151 0.78334143 0.47860917]
 [0.81091016 0.04696872 0.47190958 0.25908439 0.06829705 0.98260616 0.06543224 0.41265921 0.41078555 0.7090427  0.55941733 0.77087253]
 [0.2892641  0.84357893 0.08144098 0.6048152  0.42480708 0.56021958 0.71202408 0.21226507 0.46442726 0.10815148 0.8481122  0.48331087]
 [0.3963784  0.63833691 0.26843028 0.2425526  0.9763138  0.5211089  0.82279802 0.02183642 0.43026491 0.04391001 0.19598927 0.57220814]
 [0.30119705 0.72588894 0.07761706 0.90425608 0.58660824 0.34791562 0.71369128 0.97586656 0.98380075 0.46411012 0.86958072 0.38341991]
 [0.39278785 0.48454093 0.03085601 0.69805807 0.36629101 0.5850471  0.0267303  0.96322582 0.41917826 0.45285395 0.50637147 0.29217256]
 [0.41910524 0.63047921 0.30055675 0.65310168 0.1670944

In [ ]:
A_inv = np.linalg.inv(A)
print(A @ A_inv)

[[ 1.  0. -0.  0. -0. -0.  0. -0. -0.  0.  0.  0.]
 [ 0.  1. -0. -0. -0.  0.  0. -0. -0. -0.  0. -0.]
 [ 0.  0.  1. -0.  0.  0.  0.  0. -0.  0.  0. -0.]
 [-0. -0.  0.  1. -0.  0. -0. -0.  0.  0. -0. -0.]
 [ 0.  0.  0. -0.  1.  0.  0. -0. -0.  0.  0.  0.]
 [ 0.  0.  0.  0. -0.  1. -0. -0. -0.  0. -0. -0.]
 [-0. -0. -0.  0. -0.  0.  1. -0.  0.  0. -0.  0.]
 [-0. -0. -0. -0.  0.  0.  0.  1. -0.  0. -0. -0.]
 [-0.  0. -0. -0. -0.  0.  0.  0.  1.  0. -0. -0.]
 [-0.  0. -0. -0. -0. -0.  0. -0. -0.  1.  0.  0.]
 [-0. -0.  0. -0.  0.  0. -0.  0.  0. -0.  1. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -0. -0.  0. -0.  1.]]


In [ ]:
A = hilbert(12)
print(A)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857 0.06666667]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857 0.06666667 0.0625    ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857 0.06666667 0.0625     0.05882353]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857 0.06666667 0.0625     0.05882353 0.05555556]
 [0.125      0.11111111 0.1        0.09090909 0.0833333

In [ ]:
A_inv = np.linalg.inv(A)
print(A @ A_inv)

[[ 1.          0.00000016  0.00000256 -0.00035053  0.00036049 -0.00145873  0.01151146 -0.01774201  0.03351967  0.00253858  0.01039209 -0.00164163]
 [-0.00000001  1.00000088 -0.00000339  0.00006534 -0.00055812  0.00566593 -0.02332128  0.05964647 -0.05482945  0.03416511 -0.00981806  0.00238862]
 [ 0.          0.00000033  1.00000655 -0.0002416   0.00189591 -0.00341273  0.01293616  0.00711399 -0.00447198 -0.01958747  0.00193206 -0.00105833]
 [-0.          0.00000013  0.00001119  0.9997239   0.00226936 -0.00966675  0.02652104 -0.03284528  0.02584456 -0.03230478  0.00432451 -0.00113399]
 [-0.00000001  0.00000077 -0.00000858  0.00002289  0.99987793  0.00292969 -0.00488281  0.03320312 -0.05859375 -0.00390625 -0.01416016  0.00085449]
 [-0.00000001  0.00000109 -0.00002103  0.00026486 -0.00145867  1.0073253  -0.0288739   0.07522384 -0.06324837  0.04720809 -0.02315461  0.0038966 ]
 [ 0.         -0.00000068  0.00003477 -0.00042951  0.0036583  -0.01602782  1.03859879 -0.04828634  0.0731277  -0.06601

### Demo 2: Ill-conditioned Matrices in Linear Regression

In [ ]:
# Create a dataset with almost linearly dependent features.
# x2 = x1 + epsilon * noise

epsilon = 1e-12   # try 1e-6, 1e-10, 1e-12 to make it worse

np.random.seed(2109)

x1 = np.random.randn(100, 1)
x2 = x1 + epsilon * np.random.randn(100, 1)

X = np.hstack([x1, x2])

# True underlying weights (well-behaved)
w_true = np.array([1.0, -1.0])

y = X @ w_true + 0.01 * np.random.randn(100)

In [ ]:
lr = LinearRegression(fit_intercept=False)
lr.fit(X, y)
w_sklearn = lr.coef_

print(f"True weights:                               {w_true}")
print(f"scikit-learn LinearRegression weights:      {w_sklearn}")

True weights:                               [ 1. -1.]
scikit-learn LinearRegression weights:      [ 1.1054302e+09 -1.1054302e+09]
